spring.application.name=WorkHub

spring.datasource.url=jdbc:postgresql://localhost:5432/workhub
spring.datasource.username=postgres
spring.datasource.password=Nikhil@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
